### ISSUE TITLE
Only Current one is shown

### ISSUE THREAD

**Issue by vpanjganj** [ianwalter/ng-breadcrumbs#40]
Hi, only my last/current breadcrumb item is shown on each view. :(

**Comment by jarzuaga** [comment]
This is happening to me as well. were you able to resolve it?

**Comment by vpanjganj** [comment]
Hi, yes I came up with a really quick embarrassing dirty hack:
In that partial HTML of breadcrumbs you can check the size of the array and show it if it's more than 1:
 something like: ng-show="breadcrumbs.breadcrumbs.length>1

Note that I have breadcrumbs in my $rootScope

**Comment by vpanjganj** [comment]
Hi,
Sorry my previous answer is totally irrelevant and I sent by accident .
What you should do is using the labels you define in each route .
Imagine you have home and setting as two routes. 
Label: 'Home'

And for the next route:
label : 'Home/Settings'


My previous reply if you're interested is for when you don't want to show breadcrumbs on a route with single label value. Like homepage 'Home'.

**Comment by NekDil** [comment]
I am facing similar problem, it's just showing the last item. When I inspect the breadcrumbs.get(), I get only one item on every page. Can anyone help me?
Here is my code snippet - in app.js.coffee
```coffee
app.run ($rootScope, $templateCache, breadcrumbs) ->
  ...
  $rootScope.breadcrumbs = breadcrumbs
  ...
```
In controller
```coffee
app.controller "ProgramsController", ($scope, $rootScope, $routeParams, breadcrumbs) ->
  ...
  $rootScope.breadcrumbs = breadcrumbs
  breadcrumbs.options = 
    'Programs': "#{p.name}"
  ...
```
Here is my config in app.js.coffee
```coffee
irisApp.config ($routeProvider, $locationProvider) ->
  $routeProvider.when '/', redirectTo: '/dashboard'
  $routeProvider.when '/dashboard', templateUrl: '/templates/dashboard.html', controller: 'DashboardController', label: 'Home'
  $routeProvider.when '/programs/:program_id', templateUrl: '/templates/programs.html', controller: 'ProgramsController', label: 'Programs'
  ...
```

**Comment by vpanjganj** [comment]
Hi, your code seems fine to me. I just don't use  "breadcrumbs.options" at all.
My code is like this:
```javascript
  $routeProvider.when('/users', {
        templateUrl: 'partials/user-manage-list.html',
        controller: 'UserController',
        label: 'Users'
    });
    $routeProvider.when('/initiate', {
        templateUrl: 'partials/email-initiate-edit.html',
        controller: 'EmailInitiateController',
        label: '1. Initiate'
    });

    $routeProvider.when('/initiate/configure', {
        templateUrl: 'partials/email-configure-edit.html',
        controller: 'EmailConfigureController',
        label: '2. Configure'
    });
```
