### ISSUE TITLE
skips a label

### ISSUE THREAD

**Issue by cskiwi** [ianwalter/ng-breadcrumbs#44]
so I have the following setup: 

```` javascript
'/': {
    location: 'Home',
    label: 'Home'
},
'/contacts': {
    location: 'contact/Contact',
    label: 'Contacts'
},
'/contact/:id':{
    location:  'contact/ContactDetail',
    label: 'Contact details'
}
````

and my labels are as following:
on the `/`route: 
````
1. Home
````

on the `/contacts` route:
````
1. Home
2. Contacts
````

on the `/contacts/5` route:
````
1. Home
2. Contact Details
````
---
Now the issue is that it doesn't show
````
1. Home
2. Contacts
3. Contact Details
````
on the `/contacts/5` route. As you would think it should do this?

**Comment by ianwalter** [comment]
It doesn't do that because 'contacts' and 'contact' routes don't match. The convention with RESTful routes would be that the details page route would be `/contacts/:id`

**Comment by cskiwi** [comment]
Wow I'm so sorry for that! wasn't fully awake apparantly :/ 
yea setting my routes right, fixed it :)
